version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mybackendtest
      POSTGRES_DB: mybackend
    volumes:
     - ./database:/var/lib/postgresql
    ports:
      - "5433:5432"